# Imagem base
FROM python:3.9

# Define o diretório de trabalho
WORKDIR /app

# Copia o código do consumidor para o contêiner
COPY consumidor.py .

# Instala as dependências necessárias
RUN pip install confluent-kafka

# Comando para executar o consumidor
CMD ["python", "consumidor.py"]
